# Generated by Django 6.0.2 on 2026-04-30 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_dailyentry_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('bills', 'Bills'), ('study', 'Study'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['user', 'date'], name='entry_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['user', 'status'], name='entry_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['user', 'category'], name='entry_user_category_idx'),
        ),
    ]
