# Generated by Django 6.0.2 on 2026-04-30 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='entry_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('task', 'Task')], db_index=True, default='expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('bills', 'Bills'), ('study', 'Study'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('other', 'Other')], db_index=True, default='other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['user', 'entry_type'], name='entry_user_type_idx'),
        ),
    ]
